### PR TITLE
multiple data atoms can cause size overflow and hang

### PR DESCRIPTION
**Pull request by hellwege**

### CODE REVIEW

**Comment by hellwege** [comment]
I will be modifying this shortly to add full support for multiple data atoms.

**Comment by hellwege** [comment]
Updated PR to support multiple data atoms.  Updated sample.mp4 with tag "release type", which contains multiple data atoms.

**Comment by dhowden** [comment]
Thanks for the contribution!

I'm pretty busy at the moment, but will hopefully get to look at this in a few days.

One thing though: the context change is API-breaking, so I would definitely put that in a seperate PR.   It seems a little off though, maybe instead we should consider setting limits on the size of metadata we will look at (if you're worried about it taking too long).

**Comment by dhowden** [comment]
This pull request is to address #50

**Comment by hellwege** [comment]
> Thanks for the contribution!
> 
> I'm pretty busy at the moment, but will hopefully get to look at this in a few days.
> 
Hi, if you are able to take a look at the change that would be much appreciated!  Thanks.

**Pull request merged**
