### PR TITLE
Add support for lyrics.

### PR DESCRIPTION
**Pull request by xhenner**
I've added a Lyrics() method and implemented on the supported formats.
Not supported in id3v1 and id3v22

### CODE REVIEW

**Comment by dhowden** [comment]
Awesome, thanks for the patch!

**Comment by dhowden** [comment]
I'm seeing a lot of errors on my MP3 files: `error decoding tag description text: invalid byte order marker 0 ff`.  This seems to be mainly from `COMM` tags, but also some `ULST` tags.

Reverting for now whilst I can work out what's going on.  Removing `COMM` support solves this for most files, but there are still a few with errors.

**Comment by xhenner** [comment]
Hum, I just check on my whole collection (I did my testing on a smaller subset). Same issue here, I will recheck.

**Comment by xhenner** [comment]
I've updated my lyrics branch with a patch
It worked on my 10k+ files this time

**Comment by dhowden** [comment]
I also wrote a patch for this, as it also affects other things.  Will reapply your other changes and add the fix.

**Pull request merged**
